#!/bin/sh
#
# codwaw startup script
#

# Function to find the real directory a program resides in.
# Feb. 17, 2000 - Sam Lantinga, Loki Entertainment Software
FindPath()
{
    fullpath="`echo $1 | grep /`"
    if [ "$fullpath" = "" ]; then
        oIFS="$IFS"
        IFS=:
        for path in $PATH
        do if [ -x "$path/$1" ]; then
               if [ "$path" = "" ]; then
                   path="."
               fi
               fullpath="$path/$1"
               break
           fi
        done
        IFS="$oIFS"
    fi
    if [ "$fullpath" = "" ]; then
        fullpath="$1"
    fi

    # Is the sed/ls magic portable?
    if [ -L "$fullpath" ]; then
        #fullpath="`ls -l "$fullpath" | awk '{print $11}'`"
        fullpath=`ls -l "$fullpath" |sed -e 's/.* -> //' |sed -e 's/\*//'`
    fi
    dirname $fullpath
}

# Set the home if not already set.
if [ "${CODWAW_DATA_PATH}" = "" ]; then
    CODWAW_DATA_PATH="`FindPath $0`/"
fi

# Let's boogie!
if [ -x "${CODWAW_DATA_PATH}/codwaw_lnxded-bin" ]
then
	cd "${CODWAW_DATA_PATH}/"
	exec "./codwaw_lnxded-bin" "$@"
fi
echo "Couldn't run Call of Duty: World at War (codwaw_lnxded-bin). Is CODWAW_DATA_PATH set?"
exit 1

# end of codwaw_lnxded ...

